# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "./shared", "/home/vagrant/shared", create: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 2
  end

  # Default playbook if ENV['PLAYBOOK'] is unset
  playbook = ENV['PLAYBOOK'] || "ovs-simple/provision.yml"

  # Array to store node names
  nodes = []

  # Define central VM
  config.vm.define "central" do |node|
    node.vm.hostname = "central"
    node.vm.network "private_network", ip: "172.16.56.10"
  end

  # only do this in the ovs-simple playbook
  if playbook.include?("ovs-simple")
    # Define node VMs and add to nodes array
    (1..2).each do |i|
      config.vm.define "node#{i}" do |node|
        node.vm.hostname = "node#{i}"
        node.vm.network "private_network", ip: "172.16.56.#{10 + i}"
        nodes << "node#{i}"
      end
    end
  end

  # Single Ansible provisioner for all VMs
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = playbook
    ansible.groups = {
      "central" => ["central"],
      "nodes" => nodes,
      "all:children" => ["central", "nodes"]
    }
  end
end
