# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "./shared", "/home/vagrant/shared"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 2
  end

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.network "private_network", ip: "172.16.56.#{1 + i}"
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = ENV['PROVISIONER']
      end
    end
  end
end
